package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/zeace/poisson/crawler/analyzer"
	"github.com/zeace/poisson/crawler/fetcher"
	"github.com/zeace/poisson/models"
)

// Analyze is the resolver for the analyze field.
func (r *mutationResolver) Analyze(ctx context.Context, url string, mode *string) (*AnalysisResult, error) {
	modeStr := "joke"
	if mode != nil {
		modeStr = *mode
	}

	// Verify mode is valid
	promptMode, err := analyzer.VerifyValidMode(modeStr)
	if err != nil {
		return nil, fmt.Errorf("invalid mode: %v", err)
	}

	// Get API key
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		// Try reading from secrets file
		secretKey, err := os.ReadFile("secrets/openai_key")
		if err == nil {
			apiKey = strings.TrimSpace(string(secretKey))
		}
	}

	if apiKey == "" {
		return nil, fmt.Errorf("OPENAI_API_KEY not set")
	}

	// Fetch article content
	page, _, err := fetcher.FetchArticleContent(ctx, url, false, r.datastoreClient)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch article: %v", err)
	}

	// Analyze content
	analysis, err := analyzer.Analyze(ctx, page, apiKey, promptMode, r.datastoreClient, false)
	if err != nil {
		return nil, fmt.Errorf("failed to analyze: %v", err)
	}

	return &AnalysisResult{
		Mode:              string(analysis.Mode),
		JokePercentage:    analysis.JokePercentage,
		JokeReasoning:     analysis.JokeReasoning,
		PromptFingerprint: analysis.PromptFingerprint,
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Analysis is the resolver for the analysis field.
func (r *queryResolver) Analysis(ctx context.Context, url string, mode *string) (*AnalysisResult, error) {
	modeStr := "joke"
	if mode != nil {
		modeStr = *mode
	}

	// Verify mode is valid
	_, err := analyzer.VerifyValidMode(modeStr)
	if err != nil {
		return nil, fmt.Errorf("invalid mode: %v", err)
	}

	// Read from datastore
	result, found, err := models.ReadAnalysisResult(ctx, r.datastoreClient, url, modeStr)
	if err != nil {
		return nil, fmt.Errorf("failed to read analysis result: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &AnalysisResult{
		Mode:              string(result.Mode),
		JokePercentage:    result.JokePercentage,
		JokeReasoning:     result.JokeReasoning,
		PromptFingerprint: result.PromptFingerprint,
	}, nil
}

// CrawledPage is the resolver for the crawledPage field.
func (r *queryResolver) CrawledPage(ctx context.Context, url string) (*CrawledPage, error) {
	page, found, err := models.ReadCrawledPage(ctx, r.datastoreClient, url)
	if err != nil {
		return nil, fmt.Errorf("failed to read crawled page: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &CrawledPage{
		URL:      page.URL,
		Title:    page.Title,
		Content:  page.Content,
		Datetime: page.DateTime.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
