package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/zeace/poisson/crawler/analyzer"
	"github.com/zeace/poisson/models"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Analysis is the resolver for the analysis field.
func (r *queryResolver) Analysis(ctx context.Context, url string, mode *string) (*AnalysisResult, error) {
	modeStr := "joke"
	if mode != nil {
		modeStr = *mode
	}

	// Verify mode is valid
	_, err := analyzer.VerifyValidMode(modeStr)
	if err != nil {
		return nil, fmt.Errorf("invalid mode: %v", err)
	}

	// Read from datastore
	result, found, err := models.ReadAnalysisResult(ctx, r.datastoreClient, url, modeStr)
	if err != nil {
		return nil, fmt.Errorf("failed to read analysis result: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &AnalysisResult{
		Mode:              string(result.Mode),
		JokePercentage:    result.JokePercentage,
		JokeReasoning:     result.JokeReasoning,
		PromptFingerprint: result.PromptFingerprint,
	}, nil
}

// CrawledPage is the resolver for the crawledPage field.
func (r *queryResolver) CrawledPage(ctx context.Context, url string) (*CrawledPage, error) {
	page, found, err := models.ReadCrawledPage(ctx, r.datastoreClient, url)
	if err != nil {
		return nil, fmt.Errorf("failed to read crawled page: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &CrawledPage{
		URL:      page.URL,
		Title:    page.Title,
		Content:  page.Content,
		Datetime: page.DateTime.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
type mutationResolver struct{ *Resolver }
*/
