package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"github.com/zeace/poisson/crawler/analyzer"
	"github.com/zeace/poisson/server"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Analysis is the resolver for the analysis field.
func (r *queryResolver) Analysis(ctx context.Context, url string, modeStr *string) (*AnalysisResult, error) {
	if modeStr == nil {
		var joke string = "joke"
		modeStr = &joke
	}

	// Verify mode is valid
	mode, err := analyzer.VerifyValidMode(*modeStr)
	if err != nil {
		return nil, fmt.Errorf("invalid mode: %v", err)
	}

	// Read from datastore
	result, found, err := r.datastoreClient.ReadAnalysisResult(ctx, url, mode)
	if err != nil {
		return nil, fmt.Errorf("failed to read analysis result: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &AnalysisResult{
		Mode:              string(result.Mode),
		JokePercentage:    result.JokePercentage,
		JokeReasoning:     result.JokeReasoning,
		PromptFingerprint: result.PromptFingerprint,
	}, nil
}

// CrawledPage is the resolver for the crawledPage field.
func (r *queryResolver) CrawledPage(ctx context.Context, url string) (*CrawledPage, error) {
	page, found, err := r.datastoreClient.ReadCrawledPage(ctx, url)
	if err != nil {
		return nil, fmt.Errorf("failed to read crawled page: %v", err)
	}

	if !found {
		return nil, nil
	}

	return &CrawledPage{
		URL:      page.URL,
		Title:    page.Title,
		Content:  page.Content,
		Datetime: page.DateTime.Format(time.RFC3339),
	}, nil
}

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, maxArticles int, oldestDate string, mode string) ([]*FeedItem, error) {
	// Parse oldestDate string to time.Time
	parsedDate, err := time.Parse(time.DateOnly, oldestDate)
	if err != nil {
		return nil, fmt.Errorf("invalid date format: %v (expected RFC3339)", err)
	}

	// Verify mode is valid
	_, err = analyzer.VerifyValidMode(mode)
	if err != nil {
		return nil, fmt.Errorf("invalid mode: %v", err)
	}

	// Call GetFeed from server package
	feedItems, err := server.GetFeed(ctx, r.datastoreClient, maxArticles, parsedDate, mode)
	if err != nil {
		return nil, fmt.Errorf("failed to get feed: %v", err)
	}

	// Convert server.FeedItem to graph.FeedItem
	result := make([]*FeedItem, len(feedItems))
	for i, item := range feedItems {
		result[i] = &FeedItem{
			URL:            item.URL,
			Title:          item.Title,
			JokeConfidence: item.JokeConfidence,
		}
	}

	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
